# Generated by Django 3.0.5 on 2021-03-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Student_username', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_password', models.CharField(blank=True, max_length=30, null=True)),
                ('Student_address', models.TextField(blank=True, null=True)),
                ('date_of_reg', models.DateField()),
            ],
        ),
    ]
