# Generated by Django 3.0.5 on 2021-03-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Course_stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
