# Generated by Django 3.0.5 on 2021-03-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_remove_tests_test_status'),
        ('LearningApp', '0007_auto_20210329_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_test_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.CharField(blank=True, max_length=10, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningApp.Students')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.Tests')),
            ],
        ),
    ]
