# Generated by Django 3.0.5 on 2021-03-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, max_length=30, null=True)),
                ('test_duration', models.IntegerField(blank=True, null=True)),
                ('test_totalmark', models.IntegerField(blank=True, null=True)),
                ('Course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseApp.Courses')),
            ],
        ),
    ]
