# Generated by Django 3.0.5 on 2021-03-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_tests_test_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='test_status',
        ),
    ]
