# Generated by Django 3.0.5 on 2021-03-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Course_description', models.TextField(blank=True, null=True)),
                ('Couser_stream', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
