# Generated by Django 3.0.5 on 2021-03-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_auto_20210329_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Couser_Image',
            field=models.ImageField(blank=True, null=True, upload_to='courseImage'),
        ),
    ]
