# Generated by Django 3.0.5 on 2021-03-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0003_courses_couser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='Couser_stream',
            new_name='Course_stream',
        ),
    ]
